//** This file is autogenerated (see scripts/update-delegates.ts). Please do not edit manually. **

import kusama from "./kusama" 
import polkadot from "./polkadot" 

export const delegateMap = {
	kusama,
	polkadot,
} 

export type SupportedChains = keyof typeof delegateMap